name: poke_team_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.0
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.1.0
  path_provider: ^2.0.11
  fluttertoast: ^8.2.2
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.7
  permission_handler:
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/assets/images/
    - .env

  fonts:
    - family: Dosis
      fonts:
        - asset: lib/assets/fonts/Dosis-VariableFont_wght.ttf
